### ISSUE TITLE
In windows, registration not saving after restart

### ISSUE THREAD

**Issue by geneeilebrecht** [TablePlus/TablePlus-Windows#135]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.28

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 85

3. The steps to reproduce this issue:

Every time I restart my computer (windows machine), the Table Plus software reverts back to free trial status and I have to re-enter my registration code.

**Comment by huyphams** [comment]
Please update to the latest release @geneiparq the issue has been resolved. We use the new installer so you have to remove the old app.
1. Open the app.
2. Open the task manager
![2019-11-19 14 02 49](https://user-images.githubusercontent.com/3654622/69173010-4c249880-0ad5-11ea-9580-84510ff47fe6.jpg)
3. Delete the folder (no data lost).
4. Download and install the latest version: https://tableplus.com/windows

Please let me know if you're still seeing the bug.

**Comment by geneiparq** [comment]
Thank you for the incredibly fast response!  I have followed the steps, and will mark this closed.

**Comment by geneiparq** [comment]
Hello,

I am still having this issue with current build 96.  Each and every time I restart my computer, the software reverts to the "free trial" version and requires me to re-enter my license key.

**Comment by huyphams** [comment]
Hi @geneiparq could you email me with more detail about your license (the email and the key) so I can check it, thank you!

**Comment by huyphams** [comment]
Sorted via email.
