### ISSUE TITLE
Newly created tables in PostgreSQL don't show in item list sidebar

### ISSUE THREAD

**Issue by libcub** [TablePlus/TablePlus-Windows#148]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
112, x-64

3. The steps to reproduce this issue:
Connected to a PostgreSQL server, do a CREATE TABLE. Commit it. It does not display in the left item list sidebar, (It does show up in the psql interactive terminal.)

When I disconnect from the server, and then reconnect, it does display.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, @libcub thank you for the feedback! This issue is addressed recently, could you please try this hot-patch and see how's it going?
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

**Comment by libcub** [comment]
Thanks for the speedy response! I downloaded the file and ran it. Unfortunately the problem persists. Is there any other info from me that would be helpful?

**Comment by huyphams** [comment]
Hi @libcub thank you for getting back to me. We misunderstood because of different use-case. I thought you created a table by clicking the button on the bottom left because you said "Commit it", but it seems like you created it by running the "CREATE TABLE ..." query.
Well, in this case, TablePlus will not reload the item on the sidebar bar, or reload the workspace content. You have to do it manually by pressing control + R, no need to restart the app.

**Comment by libcub** [comment]
Great--thanks!
