### ISSUE TITLE
Windows version doesn't show SQL Server Stored Procs and Functions

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus-Windows#54]
Shows only tables. Version 1.0 (54). 

Also, running CREATE PROCEDURE in the SQL panel gives the message "'CREATE/ALTER PROCEDURE' must be the first statement in a query batch." Will post more as they occur.

Also, all my string concatenation functions crash the app when a + used rather than CONCAT function.

**Comment by huyphams** [comment]
Hi @ayalbelling the latest version is 62, could you please update to that version and try again? a lot of improvements and bugfixes were fixed. That's why I need the reporter to include their app version in the issue.
Thank you for the feedback.

**Comment by ayalbelling** [comment]
Thanks. Apologies, I did upgrade it to 62 shortly after writing that and the SPs and functions still don't appear, just tables and views. Will attach a screenshot. Also, a query concatenating a bigint field in my case to a string which should require casting to varchar first, still crashes the app rather than reporting the cast error.

**Comment by huyphams** [comment]
Hi @ayalbelling thank for the confirmation. I'm sorry, the Windows version is not supported functions/procedure. We're working on it.
Regarding the crash issue: could you give me an example SQL? I can't reproduce it.

**Comment by huyphams** [comment]
It's supported now @ayalbelling 
<img width="673" alt="Screen Shot 2019-09-09 at 12 42 13 PM" src="https://user-images.githubusercontent.com/3654622/64545520-43f2f480-d2ff-11e9-9440-898656474984.png">
