### ISSUE TITLE
Can't connect to postgres when password contains whitespaces

### ISSUE THREAD

**Issue by damamaty** [TablePlus/TablePlus-Windows#603]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgresql 12.14

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 228

4. The steps to reproduce this issue:

Created 2 users:
 CREATE USER user1 WITH PASSWORD 'password' SUPERUSER;
 CREATE USER user2 WITH PASSWORD 'pass word' SUPERUSER;

When connecting with user2 tableplus shows 'password authentication failed for user "user2"'. Works good with user1.

**Comment by sonswift** [comment]
Hi, thank you for your feedback. The issue was fixed. The next build will be sent to you soon.

**Comment by damamaty-pinogy** [comment]
Build 232 - still doesn't work. Do you mean a next build that will be after 232?

**Comment by sonswift** [comment]
Hi @damamaty, the fix was approved after the build 232 released. In the next few days, a new build will have this fix. Thanks.

**Comment by huyphams** [comment]
Hi @damamaty if you have a chance, please try this hotpatch and see how it goes: https://www.dropbox.com/s/lw7wr2t8rsjr0l0/TablePlusUpdate.exe?dl=0
Thanks

**Comment by damamaty** [comment]
It works, thank you!
