### ISSUE TITLE
TablePlus crashes whenever I run queries or update data

### ISSUE THREAD

**Issue by ghost** [TablePlus/TablePlus-Windows#650]
This happens in all databases that are connected.
The version of the TablePlus is build 240.

**Comment by huyphams** [comment]
Please use our latest release @lglglglglglg

**Comment by ghost** [comment]
We renewed the license but it fails to update me, every time I activate the update it gets stuck in the middle.

**Comment by huyphams** [comment]
Hi @lglglglglglg you can download the app directly on our website, then reinstall it will replace the old app, it will keep your old data

**Comment by ghost** [comment]
I did that and it still doesn't work for me

**Comment by huyphams** [comment]
Could you show me the screencast or a gif? I could not reproduce/understand your issue.

**Comment by ghost** [comment]
I have nothing to show, the software simply closes every time I try to save changes or run queries.

**Comment by huyphams** [comment]
Hi @lglglglglglg I could not reproduce the issue, so I fixed some bugs blindly. I hope this addresses your problem.
https://www.dropbox.com/scl/fi/hqi17lg3wrg74deuqxpmb/TablePlusUpdate.exe?rlkey=ap8at4ntmuw4wpgas4b46797y&dl=0
Could you please install this patch and see how it goes?

**Comment by huyphams** [comment]
does it help @lglglglglglg ?

**Comment by ghost** [comment]
Sorry, I just managed to install it.
It didn't help, the problem still exists.

**Comment by huyphams** [comment]
Could you make a gif or a screencast please @lglglglglglg 
Thank you in advance.

**Comment by ghost** [comment]
https://github.com/TablePlus/TablePlus-Windows/assets/159031407/9f38f82d-6895-4c52-89ee-499758d33b05

**Comment by huyphams** [comment]
Found the issue @lglglglglglg let us fix it and send you the hotpatch shortly.

**Comment by huyphams** [comment]
Hi @lglglglglglg if you have a chance, please install this patch and see how it goes:

https://www.dropbox.com/scl/fi/hqi17lg3wrg74deuqxpmb/TablePlusUpdate.exe?rlkey=ap8at4ntmuw4wpgas4b46797y&dl=0

**Comment by ghost** [comment]
Fixed. thank you!

**Comment by csantarossa** [comment]
@huyphams It that patch still available? Every few times i run queries the app crashes :( 
I ran an update yesterday fyi !
