### ISSUE TITLE
Not possible to get space between title and text

### ISSUE THREAD

**Issue by rositapetersson** [TablePlus/TablePlus-Windows#748]
In tableplus it is not possible to get a space between the title and the text. It jumps down to the next field instead. Hope you can get it fixed soon. I have the latest version.

**Comment by sonswift** [comment]
Hi @rositapetersson,
Could you please describe more specifically where in the app you’re encountering the issue?
It would be helpful if you could provide a more detailed description and a screenshot (if possible) to help us understand the problem.
Thank you!

**Comment by rositapetersson** [comment]
> Hi [@rositapetersson](https://github.com/rositapetersson), Could you please describe more specifically where in the app you’re encountering the issue? It would be helpful if you could provide a more detailed description and a screenshot (if possible) to help us understand the problem. Thank you!

Hi!

I have record it, so you can see. Hope you see the marker, Here is the link 
https://www.awesomescreenshot.com/video/40504319?key=2bc5b9a86c5f09dbdeaca2d7bcd45a89

It jumps down to the price.

**Comment by sonswift** [comment]
Hi @rositapetersson,
I’ve identified the issue you’re experiencing and will work on fixing it. The update will be released soon.
Thank you for reporting the issue!

**Comment by huyphams** [comment]
Hi @rositapetersson in the meantime, you can right click on the cell and select quick look as a temporary solution, you can input the new line directly within the quick look editor. Thanks.

<img width="507" alt="Image" src="https://github.com/user-attachments/assets/46752988-9a43-4154-a0d9-5efbfb8d571e" />

**Comment by rositapetersson** [comment]
Hello!

No update yet, how is it going?

Mvh Rosita

Den mån 2 juni 2025 kl 12:30 skrev Henry Pham ***@***.***>:

**Comment by huyphams** [comment]
Hi @rositapetersson we fixed it but the new update has not been released. in the meantime, you can use the quick look editor as a temporary solution.
The update will be released within this month.

**Comment by rositapetersson** [comment]
Hello again!

After the update. Still the same. Se the video-link again.

Mvh Rosita


Den tis 24 juni 2025 kl 13:48 skrev Henry Pham ***@***.***>:

**Comment by sonswift** [comment]
Hi @rositapetersson, please try using Shift + Enter/Return to insert a new line within the Row Detail text field. Let us know if it works for you!

<img width="654" height="268" alt="Image" src="https://github.com/user-attachments/assets/b8e29240-ecc6-427b-808c-7a3e3f7ec10b" />

**Comment by rositapetersson** [comment]
Hi!

It works. :)

Den tors 10 juli 2025 kl 01:39 skrev Son Thai ***@***.***>:
