### ISSUE TITLE
Driver Error (Unknow Error)

### ISSUE THREAD

**Issue by horouuu** [TablePlus/TablePlus-Windows#751]
Since about two weeks ago, whenever I try to connect to a database through TablePlus, the following error appears:

![Image](https://github.com/user-attachments/assets/f21757b2-b2b7-4836-a01b-87c653ece1c9)

I have tested this with PostgreSQL and MySQL. Other database drivers have also given the same error.

I have no idea how to fix this. The following are my system details:
Microsoft Windows 11 Home v10.0.26100 Build 26100 
x64-based PC
TablePlus Version 6.5.8 (318)

If it's of any relevance, between TablePlus working and this error occurring, I updated TablePlus and also turned my BIOS' secure boot settings on and back off.

Other database clients work fine. I'd like to return to TablePlus, however 😅 

If any other details are needed, please let me know.

**Comment by jlabs** [comment]
Getting the same here. I've upgraded my work laptop and gone to use TablePlus on the new setup, but get the same error.

For me, I get the error when connecting to an external database (service running on a EC2 instance for example). Local hosted databases are fine, it's just remote ones I have the issue. 
If I enter incorrect connection details, then I get the error relating to that, so I'm guessing is is a driver error.

**Comment by huyphams** [comment]
Hi, we fixed this issue, will release update next week.
Correct @jlabs it will show unknown error when the credentials are incorrect.

**Comment by Devansh1105** [comment]
Hey the error still persists

**Comment by Devansh1105** [comment]
I am still facing the issue shows the same error for me and we have the same config.

**Comment by huyphams** [comment]
Which version are you using @Devansh1105 and which driver are you using?
